[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install", "npm --prefix ../backend install"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "node ../backend/src/server.js"
